language: python
addons:
  postgresql: "9.3"
python:
  - 2.7
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test_cmp;' -U postgres
  - export DATABASE_URL=postgres://postgres@localhost:5432/test_cmp
  - python manage.py migrate --noinput
script:
  - python manage.py test